# Generated by Django 5.1.3 on 2024-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('ST', 'Standard'), ('TA', 'Tandem'), ('EL', 'Electric')], default='ST', max_length=20),
        ),
    ]
